name: Build CFBD roster data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # daily 12:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm init -y || true
      - run: npm pkg set type=module

      - name: Run roster builder
        env:
          CFBD_KEY: ${{ secrets.CFBD_KEY }}
          TEAM: Kentucky
          YEAR: 2025
        run: node scripts/build_roster.js

      - name: Commit /data updates
        run: |
          git config user.name  "data-bot"
          git config user.email "data-bot@users.noreply.github.com"
          git add data/team/*.json
          git commit -m "Update roster data" || echo "No changes"
          git push
