name: Update Spotlight Feeds

on:
  workflow_dispatch:
    inputs:
      purge:
        description: 'Bust cache and refetch'
        required: false
        default: 'false'
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes

permissions:
  contents: write

concurrency:
  group: spotlight-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Validate with fixtures (offline)
        run: npm run test:fixtures

      - name: Build spotlight dataset
        env:
          CFBD_KEY: ${{ secrets.CFBD_KEY }}
          TEAM_ID: 96
          SEASON: 2025
        run: |
          npm run build:spotlight || echo "⚠️ provider failed — reusing cached /data"

      - name: Validate datasets (2025 enforcement)
        run: npm run validate:data

      - name: Commit /data updates
        run: |
          git config user.name "data-bot"
          git config user.email "data-bot@users.noreply.github.com"
          git add data/*.json data/team/*.json 2>/dev/null || true
          git commit -m "Update spotlight feeds" || echo "No changes"
          git push || true
