name: Update Spotlight Feeds
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm init -y || true
      - run: npm pkg set type=module

      - name: Run spotlight builder
        env:
          CFBD_KEY: ${{ secrets.CFBD_KEY }}
          TEAM: Kentucky
          YEAR: 2025
        run: node scripts/build_spotlight.js || true

      - name: Commit /data updates
        run: |
          git config user.name  "data-bot"
          git config user.email "data-bot@users.noreply.github.com"
          git add data/live/*.json data/spotlight/*.json 2>/dev/null || true
          git commit -m "Update spotlight feeds" || echo "No changes"
          git push || true
