name: Update Spotlight Feeds

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write  # needed to commit JSON back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: npm ci || npm i

      - name: Build spotlight JSON
        env:
          CFBD_KEY: ${{ secrets.CFBD_KEY }}
          YEAR: "2025"
        run: npm run build:spotlight

      - name: Build ticker JSON
        env:
          CFBD_KEY: ${{ secrets.CFBD_KEY }}
          YEAR: "2025"
        run: npm run build:ticker

      - name: Commit & push
        run: |
          git config user.name "spotlight-bot"
          git config user.email "actions@github.com"
          git add data/*.json
          git commit -m "Update spotlight/ticker feeds" || echo "No changes"
          git push
