name: Update Spotlight Feeds

on:
  workflow_dispatch:
    inputs:
      purge:
        description: 'Bust cache and refetch'
        required: false
        default: 'false'
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes

permissions:
  contents: write

concurrency:
  group: spotlight-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PURGE_REQUESTED: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.purge == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build spotlight dataset
        env:
          CFBD_KEY: ${{ secrets.CFBD_KEY }}
        run: |
          if [[ "${PURGE_REQUESTED}" == "true" ]]; then
            echo "🧹 purge mode enabled — clearing caches and refetching"
            npm run build:spotlight -- --purge
          else
            npm run build:spotlight
          fi

      - name: Validate datasets
        run: npm run validate:data

      - name: Commit /data updates
        run: |
          git config user.name "data-bot"
          git config user.email "data-bot@users.noreply.github.com"
          git add data/*.json data/team/*.json 2>/dev/null || true
          git commit -m "Update spotlight feeds" || echo "No changes"
          git push || true
