name: Spotlight datasets

on:
  schedule:
    - cron: "12,42 * * * *"   # every 30 min at :12/:42 to dodge API spikes
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set up job
        run: echo "Starting spotlight build..."

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"   # Node 20 for native fetch + perf

      - name: Install dependencies
        run: npm ci || npm i

      # Optional, harmless (prevents your earlier red X)
      - name: Validate fixtures
        run: npm run test:fixtures

      - name: Build roster + spotlight + ticker
        env:
          CFBD_KEY: ${{ secrets.CFBD_KEY }}
          TEAM: Kentucky
          YEAR: 2025
        run: node scripts/build_spotlight.js

      - name: Commit refreshed data
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@github.com"
          git add data/*.json
          git diff --quiet && echo "No data changes." || git commit -m "data: refresh spotlight/ticker/roster [ci]"
      - name: Push
        if: always()
        run: |
          git push || true
