name: Spotlight datasets

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: spotlight
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Show Node
        run: node --version

      - name: Build spotlight JSON
        env:
          CFBD_KEY: ${{ secrets.CFBD_KEY }}
          TEAM: Kentucky
          YEAR: 2025
        run: node scripts/build_spotlight.js

      - name: Commit refreshed data (only if changed)
        run: |
          git config user.name  "hashmark-bot"
          git config user.email "hashmark-bot@users.noreply.github.com"
          git add data/*.json
          # IMPORTANT: check staged diff, not worktree
          if ! git diff --cached --quiet; then
            git commit -m "Update spotlight datasets"
            git push
          else
            echo "No data changes."
          fi
