# SCHEDULED + MANUAL builder that writes data/*.json and pushes them.
# IMPORTANT FIXES:
#  - permissions: contents: write  ← required to push
#  - commit check uses staged diff (--cached) instead of worktree diff

name: Spotlight datasets

on:
  workflow_dispatch: {}
  schedule:
    - cron: "13,43 * * * *"  # every 30 min (tweak as needed)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CFBD_KEY: ${{ secrets.CFBD_KEY }}
      TEAM: Kentucky
      YEAR: 2025
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build spotlight JSON feeds
        run: node scripts/build_spotlight.js

      - name: Configure git
        run: |
          git config user.name "hc-bot"
          git config user.email "bot@hashmarkchronicles.online"

      - name: Stage data
        run: git add data/*.json

      - name: Commit if changed (staged diff)
        run: |
          if ! git diff --cached --quiet; then
            git commit -m "refresh spotlight datasets [skip ci]"
            git push
          else
            echo "No data changes"
          fi
